[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/success"
  to = "/thank-you"
  status = 200
  force = true 
  
[[redirects]]
  from = "/success/"
  to = "/thank-you"
  status = 200 
  force = true 